---

- name: Ensure Sentry is stopped
  service: name={{item}} state=stopped
  with_items:
  - sentry-web
  - sentry-worker
  - sentry-cron

- name: Remove Upstart configuration
  file: path=/etc/init/{{item}}.conf state=absent
  with_items:
    - sentry-web
    - sentry-worker
    - sentry-cron
