---

- name: sentry restart
  service: name={{item}} state=restarted
  with_items:
    - sentry-web
    - sentry-worker
    - sentry-beat

- name: sentry reload
  service: name={{item}} state=reloaded
  with_items:
    - sentry-web
    - sentry-worker
    - sentry-beat
